# configurando o prjeto

source 'https://rubygems.org'

# gem "capybara"
# gem "rspec"
# gem "selenium-webdriver"

gem "capybara",  "3.10.0"
gem "rspec",  "3.8.0"
gem "selenium-webdriver",  "3.14.0"

